# Generated by Django 4.2.2 on 2023-07-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(null=True, upload_to='school_imgs/')),
                ('addresse', models.TextField()),
                ('phoneNumber', models.CharField(max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
